---
- name: Create keyword files for Linux related packages
  copy: src={{ item }}.keywords dest=/etc/portage/package.keywords/{{ item }}
  with_items:
    - gentoo-sources
    - linux-firmware

- name: Install Linux related packages
  package: name={{ item }} state=present
  with_items:
    - gentoo-sources
    - linux-firmware
    - genkernel-next
    - eclean-kernel
    - ccache
