[theme]
theme = "solarized-dark"

[[block]]
block = "cpu"
format = "$icon $barchart"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "memory"
format = "SWAP $swap_used_percents.eng(w:2)"

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%a %Y-%b-%d %I:%M %p') "

[[block]]
block = "battery"
driver = "sysfs"
device = "BAT0"
model = "Primary"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
